/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-20-2026
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class WireDecorator {
    @AuraEnabled(Cacjheable = true)
    public static string  showMessage(){
        system.debug('hii we are learning Wire Decorator');
        return '07777777777777777777hii';
    }

}